[package]
name = "mitm-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-rustls = "0.26"
rustls = "0.23"
rustls-pki-types = "1"
webpki-roots = "0.26"
tokio = { version = "1", features = ["full"] }
mitm-core = { path = "../mitm-core" }
mitm-net = { path = "../mitm-net" }
mitm-certs = { path = "../mitm-certs" }
thiserror = "2"
tracing = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
http = { workspace = true }
bytes = { workspace = true }
indexmap = { workspace = true }
async-trait = "0.1"
